import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — JusBill",
  description: "Read JusBill's disclaimer about our free GST billing tools, tax calculations, and legal advice limitations.",
  alternates: { canonical: "https://billing.jusbill.online/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <div className="container-xl py-16 max-w-3xl mx-auto">
      <h1 className="text-4xl font-heading font-extrabold text-gray-900 mb-3">Disclaimer</h1>
      <p className="text-gray-400 text-sm mb-10">Last updated: January 15, 2024</p>

      <div className="space-y-8 text-gray-600 leading-relaxed">
        <div className="bg-yellow-50 border border-yellow-200 rounded-2xl p-6">
          <p className="font-semibold text-yellow-800">⚠️ Important Notice</p>
          <p className="mt-2 text-yellow-700">JusBill is a free online tool for generating billing documents. It does not constitute legal, financial, or tax advice. Always consult a qualified professional for your specific business needs.</p>
        </div>

        <section>
          <h2 className="text-xl font-heading font-bold text-gray-900 mb-3">No Tax / Legal Advice</h2>
          <p>The information and tools provided on JusBill are for general informational and convenience purposes only. Nothing on this website should be construed as legal, tax, financial, or accounting advice. GST laws in India are complex and frequently updated — always consult a qualified Chartered Accountant (CA) or GST practitioner for your specific business requirements.</p>
        </section>

        <section>
          <h2 className="text-xl font-heading font-bold text-gray-900 mb-3">Accuracy of Calculations</h2>
          <p>While we strive to provide accurate GST calculations, JusBill does not guarantee that all calculations are error-free for every scenario. GST rules can vary based on the nature of supply, exemptions, composition schemes, and other factors that our tool may not account for. Users are responsible for verifying calculations before using them for official tax filings.</p>
        </section>

        <section>
          <h2 className="text-xl font-heading font-bold text-gray-900 mb-3">Invoice Acceptance</h2>
          <p>JusBill generates invoice templates in a format commonly used in India. However, we do not guarantee that invoices generated by our tool will be accepted by all tax authorities, clients, banks, or other institutions in all situations. Requirements may vary.</p>
        </section>

        <section>
          <h2 className="text-xl font-heading font-bold text-gray-900 mb-3">External Links</h2>
          <p>Our website may contain links to external websites, including government GST portals and other resources. JusBill is not responsible for the content, accuracy, or availability of external sites.</p>
        </section>

        <section>
          <h2 className="text-xl font-heading font-bold text-gray-900 mb-3">Blog Content</h2>
          <p>Articles and guides published on JusBill&apos;s blog are for educational purposes only. While we try to keep content updated, GST laws change frequently. Always refer to the official GST portal (gst.gov.in) for the most current regulations.</p>
        </section>

        <section>
          <h2 className="text-xl font-heading font-bold text-gray-900 mb-3">Contact</h2>
          <p>For questions about this disclaimer, contact us at <a href="mailto:support@jusbill.online" className="text-brand-600 hover:underline">support@jusbill.online</a>.</p>
        </section>
      </div>
    </div>
  );
}
