import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — JusBill",
  description: "Read JusBill's disclaimer about our free GST billing tools, tax calculations, and legal advice limitations.",
  alternates: { canonical: "https://billing.jusbill.online/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <div className="container-xl py-16 max-w-4xl mx-auto">
      <h1 className="text-4xl sm:text-5xl font-heading font-extrabold text-gray-900 mb-4">Disclaimer</h1>
      <p className="text-gray-500 text-sm mb-12 border-b border-gray-100 pb-6">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

      <div className="space-y-10 text-gray-600 leading-relaxed">
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 shadow-sm">
          <p className="font-bold text-amber-900 flex items-center gap-2">
            <span className="text-xl">⚠️</span> Important Legal Notice
          </p>
          <p className="mt-3 text-amber-800">
            JusBill is a software-as-a-service (SaaS) platform that provides free online tools for generating billing documents. <strong>We do not provide legal, financial, accounting, or tax advice.</strong> You should always consult a qualified Chartered Accountant (CA) or tax professional for specific advice regarding your business and tax compliance.
          </p>
        </div>

        <section>
          <h2 className="text-2xl font-heading font-bold text-gray-900 mb-4">1. No Professional Tax or Legal Advice</h2>
          <p>The tools, calculators, blog articles, and formatting templates provided on JusBill (billing.jusbill.online) are intended for general informational and administrative convenience only. Nothing contained on this website should be interpreted as professional advice.</p>
          <p className="mt-3">GST laws in India, including rates for specific HSN/SAC codes, exemptions, and filing rules, are complex and subject to frequent changes by the GST Council. We make no representations that the documents generated by our tools will perfectly align with every unique tax scenario.</p>
        </section>

        <section>
          <h2 className="text-2xl font-heading font-bold text-gray-900 mb-4">2. User Responsibility to Review Documents</h2>
          <p><strong>You are strictly responsible for reviewing every invoice, receipt, or salary slip generated using JusBill before finalizing or issuing it.</strong></p>
          <p className="mt-3">It is your sole responsibility to ensure that:</p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
            <li>The calculated CGST, SGST, and IGST amounts are correct for your specific goods or services.</li>
            <li>The total amounts, item descriptions, and HSN/SAC codes are accurate.</li>
            <li>Your business details, GSTIN, and the recipient&apos;s details are correctly formatted as per the Central Goods and Services Tax Rules, 2017.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-heading font-bold text-gray-900 mb-4">3. Accuracy of Calculations</h2>
          <p>While our GST Calculator and Invoice Generator are programmed to calculate standard mathematical percentages (e.g., 5%, 12%, 18%, 28%), JusBill does not guarantee the mathematical accuracy of every generated document under all edge cases (such as complex rounding rules or reverse charge mechanisms).</p>
        </section>

        <section>
          <h2 className="text-2xl font-heading font-bold text-gray-900 mb-4">4. Acceptance of Documents</h2>
          <p>We provide standard, professional templates commonly used across India. However, we cannot guarantee that the invoices or receipts generated via JusBill will be accepted by all clients, vendors, government tax authorities, or financial institutions in all situations.</p>
        </section>

        <section>
          <h2 className="text-2xl font-heading font-bold text-gray-900 mb-4">5. Third-Party Content and Ads</h2>
          <p>JusBill may display third-party advertisements (such as Google AdSense) or link to external resources (such as the official GST portal). We do not endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site.</p>
        </section>

        <section>
          <h2 className="text-2xl font-heading font-bold text-gray-900 mb-4">6. Contact Information</h2>
          <p>For any questions regarding this disclaimer, please reach out to us at:</p>
          <p className="mt-3 font-semibold">Email: <a href="mailto:jusbill.contact@gmail.com" className="text-brand-600 hover:underline">jusbill.contact@gmail.com</a></p>
        </section>
      </div>
    </div>
  );
}
